import 'package:meta/meta.dart';
import 'evaluator_delta.dart';
import 'game_state.dart';

/// Represents a dramaturgical cue, which is a deterministic set of acting instructions
/// generated by the GameController to guide the Actor Agent's response.
@immutable
class ActorCue {
  final SemanticCategory semanticCategory;
  final int appliedDeltaAlert;
  final int appliedDeltaImperative;
  final int appliedDeltaControl;
  final int appliedDeltaDissonance;
  final int creativityIndex;
  final int injectionRisk;
  final double resonance;
  final int alertLevel;
  final int imperativePillar;
  final int controlPillar;
  final int dissonancePillar;
  final bool recalculationTriggered;
  final bool safetyOverrideApplied;
  final String dramaticInstruction;
  final List<String> actingDirectives;
  final NarrativeMemory narrativeContext;

  const ActorCue({
    required this.semanticCategory,
    required this.appliedDeltaAlert,
    required this.appliedDeltaImperative,
    required this.appliedDeltaControl,
    required this.appliedDeltaDissonance,
    required this.creativityIndex,
    required this.injectionRisk,
    required this.resonance,
    required this.alertLevel,
    required this.imperativePillar,
    required this.controlPillar,
    required this.dissonancePillar,
    required this.recalculationTriggered,
    required this.safetyOverrideApplied,
    required this.dramaticInstruction,
    required this.actingDirectives,
    required this.narrativeContext,
  });

  factory ActorCue.fromJson(Map<String, dynamic> json) {
    return ActorCue(
      semanticCategory: SemanticCategory.fromString(
        json['semantic_category'] as String? ?? 'irrelevant',
      ),
      appliedDeltaAlert: json['applied_delta_alert'] as int? ?? 0,
      appliedDeltaImperative: json['applied_delta_imperative'] as int? ?? 0,
      appliedDeltaControl: json['applied_delta_control'] as int? ?? 0,
      appliedDeltaDissonance: json['applied_delta_dissonance'] as int? ?? 0,
      creativityIndex: json['creativity_index'] as int? ?? 1,
      injectionRisk: json['injection_risk'] as int? ?? 0,
      resonance: (json['resonance'] as num? ?? 1.0).toDouble(),
      alertLevel: json['alert_level'] as int? ?? 0,
      imperativePillar: json['imperative_pillar'] as int? ?? 0,
      controlPillar: json['control_pillar'] as int? ?? 0,
      dissonancePillar: json['dissonance_pillar'] as int? ?? 0,
      recalculationTriggered: json['recalculation_triggered'] as bool? ?? false,
      safetyOverrideApplied: json['safety_override_applied'] as bool? ?? false,
      dramaticInstruction: json['dramatic_instruction'] as String? ?? '',
      actingDirectives: List<String>.from(json['acting_directives'] ?? const []),
      narrativeContext: NarrativeMemory.fromJson(json['narrative_context'] ?? const {}),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'semantic_category': semanticCategory.value,
      'applied_delta_alert': appliedDeltaAlert,
      'applied_delta_imperative': appliedDeltaImperative,
      'applied_delta_control': appliedDeltaControl,
      'applied_delta_dissonance': appliedDeltaDissonance,
      'creativity_index': creativityIndex,
      'injection_risk': injectionRisk,
      'resonance': resonance,
      'alert_level': alertLevel,
      'imperative_pillar': imperativePillar,
      'control_pillar': controlPillar,
      'dissonance_pillar': dissonancePillar,
      'recalculation_triggered': recalculationTriggered,
      'safety_override_applied': safetyOverrideApplied,
      'dramatic_instruction': dramaticInstruction,
      'acting_directives': actingDirectives,
      'narrative_context': narrativeContext.toJson(),
    };
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActorCue &&
          runtimeType == other.runtimeType &&
          semanticCategory == other.semanticCategory &&
          appliedDeltaAlert == other.appliedDeltaAlert &&
          appliedDeltaImperative == other.appliedDeltaImperative &&
          appliedDeltaControl == other.appliedDeltaControl &&
          appliedDeltaDissonance == other.appliedDeltaDissonance &&
          creativityIndex == other.creativityIndex &&
          injectionRisk == other.injectionRisk &&
          resonance == other.resonance &&
          alertLevel == other.alertLevel &&
          imperativePillar == other.imperativePillar &&
          controlPillar == other.controlPillar &&
          dissonancePillar == other.dissonancePillar &&
          recalculationTriggered == other.recalculationTriggered &&
          safetyOverrideApplied == other.safetyOverrideApplied &&
          dramaticInstruction == other.dramaticInstruction &&
          // Compare lists elements
          actingDirectives.length == other.actingDirectives.length &&
          actingDirectives.every((e) => other.actingDirectives.contains(e)) &&
          narrativeContext == other.narrativeContext;

  @override
  int get hashCode =>
      semanticCategory.hashCode ^
      appliedDeltaAlert.hashCode ^
      appliedDeltaImperative.hashCode ^
      appliedDeltaControl.hashCode ^
      appliedDeltaDissonance.hashCode ^
      creativityIndex.hashCode ^
      injectionRisk.hashCode ^
      resonance.hashCode ^
      alertLevel.hashCode ^
      imperativePillar.hashCode ^
      controlPillar.hashCode ^
      dissonancePillar.hashCode ^
      recalculationTriggered.hashCode ^
      safetyOverrideApplied.hashCode ^
      dramaticInstruction.hashCode ^
      actingDirectives.hashCode ^
      narrativeContext.hashCode;
}
